block_cipher = None

a = Analysis(['keep_route\\keep_route.py'],
             pathex=['.', '.\\keep_route'],
             binaries=[],
             datas=[('.\\version.json', '.\\')],
             hiddenimports=['pystray._win32'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.datas,
          Tree('resources', prefix='resources\\'),
          a.zipfiles,
          a.datas,
          [],
          name='keep-route',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None,
          uac_admin=True,
          icon='resources\\keep-route.ico')
